#MongoDB config
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: work-itemDB

#RabbitMQ settings
rabbitmq:
  host: localhost
  virtualhost: /
  port: 15672
  username: guest
  password: guest
  exchange: work-item-exchange
  queue: work-items
  routingkey: work-item-routingkey
  reply:
    timeout: 60000
  concurrent:
    consumers: 1
  max:
    concurrent:
      consumers: 1

#swagger settings
application:
  version: v1